name: pr-size-labeler

on: [pull_request]

jobs:
  clear-label:
    permissions:
      pull-requests: write
      contents: read
      issues: write
    runs-on: [runner-base]
    name: Clear label
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          fail_on_error: false
          labels: |
            size/xs
            size/s
            size/m
            size/l
            size/xl
  labeler:
    needs: clear-label
    permissions:
      pull-requests: write
      contents: read
      issues: write
    runs-on: [runner-base]
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          xs_label: "size/xs"
          xs_max_size: "10"
          s_label: "size/s"
          s_max_size: "100"
          m_label: "size/m"
          m_max_size: "500"
          l_label: "size/l"
          l_max_size: "1000"
          xl_label: "size/xl"
          fail_if_xl: "false"
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          github_api_url: "https://api.github.com"
          files_to_ignore: "*.lock *.json"

